
name: CI


on:

  push:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build-test-push:          
    runs-on: ubuntu-latest
    container: 
      image: gradle:7.2.0-jdk11
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: gradle build

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: olegidse/survey-api
            tags: latest, ${{ github.run_number }}

